name: CI/CD to Debian VM with Docker Compose

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: olymahmudmugdho/gcp-gh-actions-todo-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: SSH & Deploy using Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            rm -rf ~/gcp-gh-actions-todo-api
            git clone https://github.com/OlyMahmudMugdho/gcp-gh-actions-todo-api
            cd ~/gcp-gh-actions-todo-api
            docker-compose up -d
